apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/todo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
